name: signup_login
description: "A new Flutter project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  core_ui:
    path: ..\..\core_ui
  vector_graphics: ^1.1.11+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
